package com.filipcygan.buidlingsOntology;

public enum BuildingTypes {
    ArchitecturalStructure("Struktura architektoniczna"),
    Abbey("Opactwo"),
    Airfield("Lotnisko"),
    Airport("Lotnisko"),
    AmusementParkAttraction("Atrakcja parku rozrywki"),
    Arena("Arena"),
    Basilica("Bazylika"),
    Bridge("Most"),
    Building("Budynek"),
    Casino("Kazyno"),
    Castle("Zamek"),
    Cathedral("Katedra"),
    Church("Kosciół"),
    CityHall("Ratusz"),
    CricketGround("Boisko do Krykieta"),
    Dam("Zapora"),
    Dike("Wał"),
    ElectricalSubstation("Stacja elektroenergetyczna"),
    Factory("Fabryka"),
    FillingStation("Stacja benzynowa"),
    Fortification("Fortyfikacja"),
    Fort("Fort"),
    Gallery("Galeria"),
    Gate("Brama"),
    GhostTown("Wymarłe miasto"),
    GolfCourse("Pole golfowe"),
    HistoricBuilding("Zabytek"),
    Hospital("Szpital"),
    Hotel("Hotel"),
    Infrastructure("Infrastruktura"),
    LaunchPad("Wyrzutnia"),
    Lighthouse("Latarnia morska"),
    Library("Biblioteka"),
    Lock("Śluza wodna"),
    Manor("Posiadłość"),
    Mansion("Rezydencja"),
    MetroStation("Stacja metra"),
    MilitaryStructure("Jednostka wojskowa"),
    Mill("Młyn"),
    Monastery("Klasztor"),
    Mosque("Meczet"),
    Museum("Muzeum"),
    NuclearPowerStation("Elektrownia jądrowa"),
    Palace("Pałac"),
    PaleoanthropologicalSites("Stanowisko archeologiczne"),
    Park("Park"),
    Port("Port"),
    PowerStation("Elektrownia"),
    Prison("Więzienie"),
    ProvingGrounds("Poligon"),
    Pyramid("Piramida"),
    Racecourse("Tor wyścigowy"),
    RaceTrack("Tor"),
    RailwayLine("Linia kolejowa"),
    RailwayStation("Stacja kolejowa"),
    RailwayTunnel("Tunel kolejowy"),
    ReligiousBuilding("Budynek religijny"),
    RestArea("Miejsce obsługi podróżnych"),
    Restaurant("Restauracja"),
    Road("Droga"),
    RoadJunction("Skrzyżowanie"),
    RoadTunnel("Tunel drogowy"),
    RollerCoaster("Kolejka górska"),
    RouteOfTransportation("Droga"),
    Rotunda("Rotunda"),
    Ruin("Ruiny"),
    ShoppingCenter("Centrum handlowe"),
    ShoppingMall("Centrum handlowe"),
    Shrine("Kapliczka"),
    SkiArea("Teren narciarski"),
    SkiResort("Ośrodek narciarski"),
    Skyscraper("Drapacz chmur"),
    SportFacility("Obiekt Sportowy"),
    Square("Plac"),
    Stadium("Stadion"),
    Station("Stacja"),
    Street("Ulica"),
    Synagogue("Synagoga"),
    Temple("Świątynia"),
    Theater("Teatr"),
    Theatre("Teatr"),
    Tower("Wieża"),
    Town("Miasto"),
    TramStation("Przystanek tramwajowy"),
    Treadmill("kierat"),
    Tunnel("Tunel"),
    Venue("Miejsce"),
    Wall("Mur"),
    Watermill("Młyn wodny"),
    WaterRide("Zjeżdżalnia wodna"),
    WaterTower("Wieża ciśnień"),
    WaterwayTunnel("Tunel śródlądowy"),
    Windmill("Młyn"),
    WindMotor("Wiatrak"),
    Zoo("Zoo");


    private String name;

    BuildingTypes(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}